name: Docker Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Build Docker image
      run: docker build -t jupyter-test-image .

    - name: Run Docker container
      run: |
        docker run -d -p 8888:8888 --name jupyter_test_container jupyter-test-image
        sleep 10 # Esperar a que el contenedor esté listo

    - name: Stop and remove Docker container
      run: |
        docker stop jupyter_test_container
        docker rm jupyter_test_container
